// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ponto-inteligente/Access.tsx": () => import("../components/mockups/ponto-inteligente/Access.tsx"),
  "./components/mockups/ponto-inteligente/Capture.tsx": () => import("../components/mockups/ponto-inteligente/Capture.tsx"),
  "./components/mockups/ponto-inteligente/Compliance.tsx": () => import("../components/mockups/ponto-inteligente/Compliance.tsx"),
  "./components/mockups/ponto-inteligente/Dashboard.tsx": () => import("../components/mockups/ponto-inteligente/Dashboard.tsx"),
  "./components/mockups/ponto-inteligente/Home.tsx": () => import("../components/mockups/ponto-inteligente/Home.tsx"),
  "./components/mockups/ponto-inteligente/Receipt.tsx": () => import("../components/mockups/ponto-inteligente/Receipt.tsx"),
  "./components/mockups/ponto-inteligente/Timesheet.tsx": () => import("../components/mockups/ponto-inteligente/Timesheet.tsx"),
  "./components/mockups/templates/WarmLanguageLearningDashboard-PGCvPO/App.tsx": () => import("../components/mockups/templates/WarmLanguageLearningDashboard-PGCvPO/App.tsx")
};
